name: smash_import_export_plugins
description: Import/Export plugins for SMASH
version: 0.0.1
# homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  intl: '>=0.16.1 <=0.17.0'

  dart_hydrologis_db: ^0.7.1
  # path: ../dart_hydrologis_db/
  # git:
  #  url: https://github.com/moovida/dart_hydrologis_db.git
  smashlibs:
    # path: ../smashlibs/
    git:
      url: https://github.com/moovida/smashlibs.git
      ref: 399f9c3

  # apache 2
  flutter_geopackage: ^0.5.1

  dart_hydrologis_utils: ^0.6.0
    # path: ../dart_hydrologis_utils/
  dart_jts: ^0.2.0
    # path: ../dart_jts/


  xml: '>=4.5.1 <=5.3.1'

  # Apache 2.0
  gpx: ^2.1.0
    # git:
    #   url: https://github.com/moovida/dart-gpx.git
    #   ref: "540e167"

  # Apache 2.0
  pdf: '>=2.1.0 <=3.6.0'


dev_dependencies:
  test: ^1.20.1
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
  class_name: IEL # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
